version: "3.7"

services:
  buildr:
    network_mode:  none
     
    volumes:
      - ./buildr/bin:/home/buildr/bin:ro
      - ./buildr/tmp:/home/buildr/tmp:rw
      - ./buildr/source:/home/buildr/source:ro
      - ./buildr/keys:/home/buildr/keys:rw

    build:
      context: buildr
      dockerfile: Dockerfile

      args:
        lib_vrs: 2

#menn채채n nin ett채 d-c -f c3 run buildr
#aiemmin Dockerfileess채 sanottiin cmd su buildr
    entrypoint: su buildr

  buildr2:
    network_mode:  none
    volumes:
      - ./buildr/bin:/home/buildr/bin:ro
      - ./buildr/tmp:/home/buildr/tmp:rw
      - ./buildr/source:/home/buildr/source:ro
      - ./buildr/keys:/home/buildr/keys:rw

    network_mode:  none

    build:
      context: buildr
      dockerfile: Dockerfile

#huom. args on tarpeellinen
      args:
        lib_vrs: 2

    entrypoint: su buildr -c cd;./bin/FIRST_RUN.sh;exit

#TODO:buildr3, jos mahd ni s.e. avaa picoon tai jonkin konftsdton ennen FIRST_RUN
