version: "3.7"

secrets:
  backend_env:
    file: ./buildr/tmp/backend/.pgpass
#
#  backend_env2:
#    file: ./buildr/tmp/backend/.pgU

  tstr_pgpass:
    file: ./buildr/tmp/kronos/.pgpass

#HUOM.24.11.23:on jo installointiskriptin osana, tedtaus vielä
#HUOM. installointiskritin osana oltava myös possujunan deletointi (on jo 241123)
#HUOM.08102023:sittenkin possu 15?
#HUOM.21.11.23:SITTENKIN PAREMPI AJAA backend EIKÄ backend2 , DEBUG VOI KESTÄÄ MUUTEN
#VAIH:kannan toimintaa testaava kontti luotava

services:

  backend:
    image: postgres:15-alpine 

#secrets ja network_mode uusia
    network_mode: none

    secrets:
      - backend_env
#      - backend_env2
    
    env_file: 
      - ./buildr/tmp/backend/.env

#HUOM.281223:/1 ja /2 uusia
    volumes:  
      - ./buildr/tmp/sql/1:/docker-entrypoint-initdb.d:ro
      - /run/postgresql:/run/postgresql:rw
      - ./buildr/tmp/sql/2:/tmp:ro

#    command: postgres  -c hba_file=/tmp/pg_hba.conf -c config_file=/tmp/my.post.conf

  backend2:
    image: postgres:15-alpine 
    network_mode: none

    secrets:
      - backend_env
 #     - backend_env2
    
    env_file: 
      - ./buildr/tmp/backend/.env

#HUOM.281223:täälläkin vähän uusicksi , /1 ja /2 mukaan
    volumes:  
      - ./buildr/tmp/sql/1:/docker-entrypoint-initdb.d:ro
      - /run/postgresql:/run/postgresql:rw
      - ./buildr/tmp/sql/2:/tmp:ro
      - ./project/backend/possujuna:/var/lib/postgresql/data:rw

    #HUOM.261123:oltava nimenomaan my.post , ei my.post.conf
    command: postgres -c hba_file=/tmp/pg_hba.conf -c config_file=/tmp/my.post

  tstr:
    network_mode: none

    depends_on:
      - backend2

    secrets:
      - tstr_pgpass

    env_file: 
         ./buildr/tmp/kronos/.env   

    volumes:
       - /run/postgresql:/run/postgresql:rw

    build:
      context: buildr
      dockerfile: Dockerfile.t

    entrypoint: su tstr
    # -c cd;./bin/doIt.sh;exit
