version: "3.7"

services:
#toinenkin prebuild voisi löytyä deb-sukuisia kontteja varten (se .gpg ja mahd jotain .deb)
#jokin minideb kai löytyi... bitnami saattoi liittyä
  prebuild:
    volumes:
      - ./buildr/tmp:/tmp:rw
      
    build:
      context: ./buildr/pre
      dockerfile: Dockerfile3
      
    entrypoint: /doIt.sh
    
#  prebuild2:
#    volumes:
#      - ./buildr/tmp:/tmp:rw
#        
#    build:
#      context: ./buildr/pre
#      dockerfile: Dockerfile6
#      
#    entrypoint: /app/doIt.sh
#    #//bin/sh
   
